### ISSUE TITLE
webonyx/graphql-php v15 not supported

### ISSUE THREAD

**Issue by Danbka** [ivome/graphql-relay-php#24]
`
composer require ivome/graphql-relay-php
`
gives an error:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires ivome/graphql-relay-php ^0.6.0 -> satisfiable by ivome/graphql-relay-php[v0.6.0].
>     - ivome/graphql-relay-php v0.6.0 requires webonyx/graphql-php ^14.0 -> found webonyx/graphql-php[v14.0.0, ..., v14.11.9] but it conflicts with your root composer.json require (^15).

**Comment by bohlken34** [comment]
Hi @ivome! I see that you merged [https://github.com/ivome/graphql-relay-php/pull/25](https://github.com/ivome/graphql-relay-php/pull/25), which should address this. I know it's not very big, but are you planning to publish a release for this update? Thanks!

**Comment by Danbka** [comment]
Hi @ivome! Are you going to publish a release with this update to support webonyx/graphql-php:15? Thx!

**Comment by ivome** [comment]
@Danbka @bohlken34  I just published a new release `v0.7.0`. Sorry for the delay. Hope that helps.
